controller_manager:
  ros__parameters:
    update_rate: 1000
    effort_controller:
      type: effort_controllers/JointGroupEffortController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
effort_controller:
  ros__parameters:
    joints:
    - joint1
    - joint2
    - joint3
