pino_armkine_node :
    ros__parameters:
      kp: 5.0
      kd: 2000.0
      joint1: -45.0
      joint2: 135.0
      joint3: 90.0
      b: 2.0
      Ntest: 50
      errposkp: 10.0
      errposkd: 0.5
      errposki: 0.1
      errposoutlimit: 10.0
      errposinterlimit: 1.0
      errvelkp: 1.0
      errvelkd: 0.0
      errvelki: 0.1
      errveloutlimit:  15.0
      errvelinterlimit: 1.0
      errwristkp: 1.0
      errwristkd: 0.0
      errwristki: 0.1
      errwristoutlimit:  25.0
      errwristinterlimit: 1.0
      Vmax: 0.1
      Nzwz : 200
